In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv('../M1_final.csv')
df

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_DELAY,CRS_ELAPSED_TIME,DISTANCE,CRS_DEP_M,...,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Condition,sch_dep,sch_arr,TAXI_OUT
0,11,1,5,B6,N828JB,CHS,-1,124,636,324,...,34,58,W,25,38,29.86,Fair / Windy,9,17,14
1,11,1,5,B6,N992JB,LAX,-7,371,2475,340,...,34,58,W,25,38,29.86,Fair / Windy,9,17,15
2,11,1,5,B6,N959JB,FLL,40,181,1069,301,...,34,58,W,25,38,29.86,Fair / Windy,9,17,22
3,11,1,5,B6,N999JQ,MCO,-2,168,944,345,...,34,58,W,25,38,29.86,Fair / Windy,9,17,12
4,11,1,5,DL,N880DN,ATL,-4,139,760,360,...,32,58,W,24,35,29.91,Fair / Windy,9,17,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28815,1,31,5,B6,N216JB,ORH,2,57,150,1370,...,38,96,N,6,0,30.18,Cloudy,20,32,19
28816,1,31,5,AA,N104NN,BOS,2,75,187,1390,...,38,96,N,6,0,30.18,Cloudy,19,23,22
28817,1,31,5,AS,N581AS,SEA,283,392,2422,1125,...,38,96,N,6,0,30.18,Cloudy,19,23,21
28818,1,31,5,B6,N957JB,SJU,5,224,1598,1417,...,38,96,N,6,0,30.18,Cloudy,19,23,13
28819,1,31,5,B6,N958JB,BQN,-1,225,1576,1439,...,38,96,N,6,0,30.18,Cloudy,19,23,15

In [17]:
data = df.reset_index(drop=True)

In [19]:
data

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_DELAY,CRS_ELAPSED_TIME,DISTANCE,CRS_DEP_M,...,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Condition,sch_dep,sch_arr,TAXI_OUT
0,11,1,5,B6,N828JB,CHS,-1,124,636,324,...,34,58,W,25,38,29.86,Fair / Windy,9,17,14
1,11,1,5,B6,N992JB,LAX,-7,371,2475,340,...,34,58,W,25,38,29.86,Fair / Windy,9,17,15
2,11,1,5,B6,N959JB,FLL,40,181,1069,301,...,34,58,W,25,38,29.86,Fair / Windy,9,17,22
3,11,1,5,B6,N999JQ,MCO,-2,168,944,345,...,34,58,W,25,38,29.86,Fair / Windy,9,17,12
4,11,1,5,DL,N880DN,ATL,-4,139,760,360,...,32,58,W,24,35,29.91,Fair / Windy,9,17,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28815,1,31,5,B6,N216JB,ORH,2,57,150,1370,...,38,96,N,6,0,30.18,Cloudy,20,32,19
28816,1,31,5,AA,N104NN,BOS,2,75,187,1390,...,38,96,N,6,0,30.18,Cloudy,19,23,22
28817,1,31,5,AS,N581AS,SEA,283,392,2422,1125,...,38,96,N,6,0,30.18,Cloudy,19,23,21
28818,1,31,5,B6,N957JB,SJU,5,224,1598,1417,...,38,96,N,6,0,30.18,Cloudy,19,23,13
28819,1,31,5,B6,N958JB,BQN,-1,225,1576,1439,...,38,96,N,6,0,30.18,Cloudy,19,23,15

In [10]:
# Load data and reset index to remove unnamed index column
data = pd.read_csv('../M1_final.csv')
data = data.reset_index(drop=True)  # This ensures clean index without unnamed column
data

Shape: (28820, 23)
Columns: 23

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_DELAY,CRS_ELAPSED_TIME,DISTANCE,CRS_DEP_M,...,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Condition,sch_dep,sch_arr,TAXI_OUT
0,11,1,5,B6,N828JB,CHS,-1,124,636,324,...,34,58,W,25,38,29.86,Fair / Windy,9,17,14
1,11,1,5,B6,N992JB,LAX,-7,371,2475,340,...,34,58,W,25,38,29.86,Fair / Windy,9,17,15
2,11,1,5,B6,N959JB,FLL,40,181,1069,301,...,34,58,W,25,38,29.86,Fair / Windy,9,17,22
3,11,1,5,B6,N999JQ,MCO,-2,168,944,345,...,34,58,W,25,38,29.86,Fair / Windy,9,17,12
4,11,1,5,DL,N880DN,ATL,-4,139,760,360,...,32,58,W,24,35,29.91,Fair / Windy,9,17,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28815,1,31,5,B6,N216JB,ORH,2,57,150,1370,...,38,96,N,6,0,30.18,Cloudy,20,32,19
28816,1,31,5,AA,N104NN,BOS,2,75,187,1390,...,38,96,N,6,0,30.18,Cloudy,19,23,22
28817,1,31,5,AS,N581AS,SEA,283,392,2422,1125,...,38,96,N,6,0,30.18,Cloudy,19,23,21
28818,1,31,5,B6,N957JB,SJU,5,224,1598,1417,...,38,96,N,6,0,30.18,Cloudy,19,23,13
28819,1,31,5,B6,N958JB,BQN,-1,225,1576,1439,...,38,96,N,6,0,30.18,Cloudy,19,23,15

Data without index column:
 MONTH  DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER TAIL_NUM DEST  DEP_DELAY  CRS_ELAPSED_TIME  DISTANCE  CRS_DEP_M  DEP_TIME_M  CRS_ARR_M  Temperature Dew Point  Humidity Wind  Wind Speed  Wind Gust  Pressure    Condition  sch_dep  sch_arr  TAXI_OUT
    11             1            5                B6   N828JB  CHS         -1               124       636        324         323        448           48        34        58    W          25         38     29.86 Fair / Windy        9       17        14
    11             1            5                B6   N992JB  LAX         -7               371      2475        340         333        531           48        34        58    W          25         38     29.86 Fair / Windy        9       17        15
    11             1            5                B6   N959JB  FLL         40               181      1069        301         341        482           48        34        58    W          25         38     29.86 Fair / Windy        9       17        22

================================================================================

Alternative - setting index name to empty:
First 3 rows:

,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,OP_UNIQUE_CARRIER,TAIL_NUM,DEST,DEP_DELAY,CRS_ELAPSED_TIME,DISTANCE,CRS_DEP_M,...,Dew Point,Humidity,Wind,Wind Speed,Wind Gust,Pressure,Condition,sch_dep,sch_arr,TAXI_OUT
,,,,,,,,,,,,,,,,,,,,,
0,11,1,5,B6,N828JB,CHS,-1,124,636,324,...,34,58,W,25,38,29.86,Fair / Windy,9,17,14
1,11,1,5,B6,N992JB,LAX,-7,371,2475,340,...,34,58,W,25,38,29.86,Fair / Windy,9,17,15
2,11,1,5,B6,N959JB,FLL,40,181,1069,301,...,34,58,W,25,38,29.86,Fair / Windy,9,17,22

In [20]:
# Let's examine what happens with reset_index() step by step

# First, let's see the original dataframe
print("Original dataframe:")
df_original = pd.read_csv('../M1_final.csv')
print(f"Original index: {df_original.index}")
print(f"Original columns: {list(df_original.columns)}")
print("\nFirst few rows:")
print(df_original.head())

Original dataframe:
Original index: RangeIndex(start=0, stop=28820, step=1)
Original columns: ['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'TAIL_NUM', 'DEST', 'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M', 'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'sch_dep', 'sch_arr', 'TAXI_OUT']

First few rows:
   MONTH  DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER TAIL_NUM DEST  \
0     11             1            5                B6   N828JB  CHS
1     11             1            5                B6   N992JB  LAX
2     11             1            5                B6   N959JB  FLL
3     11             1            5                B6   N999JQ  MCO
4     11             1            5                DL   N880DN  ATL

   DEP_DELAY  CRS_ELAPSED_TIME  DISTANCE  CRS_DEP_M  ...  Dew Point  Humidity  \
0         -1               124       636        324  ...         34        58
1         -7               371      2475        340  ...         34        58
2         40               181      1069        301  ...         34        58
3         -2               168       944        345  ...         34        58
4         -4               139       760        360  ...         32        58

   Wind Wind Speed  Wind Gust Pressure     Condition  sch_dep  sch_arr  \
0     W         25         38    29.86  Fair / Windy        9       17
1     W         25         38    29.86  Fair / Windy        9       17
2     W         25         38    29.86  Fair / Windy        9       17
3     W         25         38    29.86  Fair / Windy        9       17
4     W         24         35    29.91  Fair / Windy        9       17

  TAXI_OUT
0       14
1       15
2       22
3       12
4       13

[5 rows x 23 columns]

In [21]:
# Now let's see what happens with reset_index() WITHOUT drop=True
print("\n" + "="*50)
print("Using reset_index() WITHOUT drop=True:")
df_reset_no_drop = df_original.reset_index()
print(f"New index: {df_reset_no_drop.index}")
print(f"New columns: {list(df_reset_no_drop.columns)}")
print("\nFirst few rows:")
print(df_reset_no_drop.head())

==================================================
Using reset_index() WITHOUT drop=True:
New index: RangeIndex(start=0, stop=28820, step=1)
New columns: ['index', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'TAIL_NUM', 'DEST', 'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M', 'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'sch_dep', 'sch_arr', 'TAXI_OUT']

First few rows:
   index  MONTH  DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER TAIL_NUM DEST  \
0      0     11             1            5                B6   N828JB  CHS
1      1     11             1            5                B6   N992JB  LAX
2      2     11             1            5                B6   N959JB  FLL
3      3     11             1            5                B6   N999JQ  MCO
4      4     11             1            5                DL   N880DN  ATL

   DEP_DELAY  CRS_ELAPSED_TIME  DISTANCE  ...  Dew Point  Humidity  Wind  \
0         -1               124       636  ...         34        58     W
1         -7               371      2475  ...         34        58     W
2         40               181      1069  ...         34        58     W
3         -2               168       944  ...         34        58     W
4         -4               139       760  ...         32        58     W

   Wind Speed Wind Gust  Pressure     Condition  sch_dep  sch_arr  TAXI_OUT
0          25        38     29.86  Fair / Windy        9       17        14
1          25        38     29.86  Fair / Windy        9       17        15
2          25        38     29.86  Fair / Windy        9       17        22
3          25        38     29.86  Fair / Windy        9       17        12
4          24        35     29.91  Fair / Windy        9       17        13

[5 rows x 24 columns]

In [22]:
# Now let's see what happens with reset_index() WITH drop=True
print("\n" + "="*50)
print("Using reset_index() WITH drop=True:")
df_reset_with_drop = df_original.reset_index(drop=True)
print(f"New index: {df_reset_with_drop.index}")
print(f"New columns: {list(df_reset_with_drop.columns)}")
print("\nFirst few rows:")
print(df_reset_with_drop.head())

==================================================
Using reset_index() WITH drop=True:
New index: RangeIndex(start=0, stop=28820, step=1)
New columns: ['MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'OP_UNIQUE_CARRIER', 'TAIL_NUM', 'DEST', 'DEP_DELAY', 'CRS_ELAPSED_TIME', 'DISTANCE', 'CRS_DEP_M', 'DEP_TIME_M', 'CRS_ARR_M', 'Temperature', 'Dew Point', 'Humidity', 'Wind', 'Wind Speed', 'Wind Gust', 'Pressure', 'Condition', 'sch_dep', 'sch_arr', 'TAXI_OUT']

First few rows:
   MONTH  DAY_OF_MONTH  DAY_OF_WEEK OP_UNIQUE_CARRIER TAIL_NUM DEST  \
0     11             1            5                B6   N828JB  CHS
1     11             1            5                B6   N992JB  LAX
2     11             1            5                B6   N959JB  FLL
3     11             1            5                B6   N999JQ  MCO
4     11             1            5                DL   N880DN  ATL

   DEP_DELAY  CRS_ELAPSED_TIME  DISTANCE  CRS_DEP_M  ...  Dew Point  Humidity  \
0         -1               124       636        324  ...         34        58
1         -7               371      2475        340  ...         34        58
2         40               181      1069        301  ...         34        58
3         -2               168       944        345  ...         34        58
4         -4               139       760        360  ...         32        58

   Wind Wind Speed  Wind Gust Pressure     Condition  sch_dep  sch_arr  \
0     W         25         38    29.86  Fair / Windy        9       17
1     W         25         38    29.86  Fair / Windy        9       17
2     W         25         38    29.86  Fair / Windy        9       17
3     W         25         38    29.86  Fair / Windy        9       17
4     W         24         35    29.91  Fair / Windy        9       17

  TAXI_OUT
0       14
1       15
2       22
3       12
4       13

[5 rows x 23 columns]

In [23]:
# EXPLANATION of what's happening:
print("\n" + "="*50)
print("EXPLANATION:")
print("="*50)
print("1. ORIGINAL dataframe:")
print("   - Has a RangeIndex (0, 1, 2, 3, ...) - this is the 'unnamed index'")
print("   - Has 23 columns of actual data")
print()
print("2. reset_index() WITHOUT drop=True:")
print("   - Creates a NEW RangeIndex (0, 1, 2, 3, ...) - this is the new 'unnamed index'")
print("   - Takes the OLD index and makes it a COLUMN called 'index'")
print("   - Now has 24 columns: the new 'index' column + 23 original data columns")
print("   - Result: You see BOTH an unnamed index AND an 'index' column")
print()
print("3. reset_index() WITH drop=True:")
print("   - Creates a NEW RangeIndex (0, 1, 2, 3, ...) - this is the new 'unnamed index'")
print("   - DROPS/DISCARDS the old index instead of making it a column")
print("   - Still has 23 columns of data (same as original)")
print("   - Result: You only see the unnamed index, no 'index' column")
print()
print("The 'unnamed index' you see is just how pandas displays the row numbers.")
print("It's not actually a column - it's the index of the dataframe.")

==================================================
EXPLANATION:
==================================================
1. ORIGINAL dataframe:
   - Has a RangeIndex (0, 1, 2, 3, ...) - this is the 'unnamed index'
   - Has 23 columns of actual data

2. reset_index() WITHOUT drop=True:
   - Creates a NEW RangeIndex (0, 1, 2, 3, ...) - this is the new 'unnamed index'
   - Takes the OLD index and makes it a COLUMN called 'index'
   - Now has 24 columns: the new 'index' column + 23 original data columns
   - Result: You see BOTH an unnamed index AND an 'index' column

3. reset_index() WITH drop=True:
   - Creates a NEW RangeIndex (0, 1, 2, 3, ...) - this is the new 'unnamed index'
   - DROPS/DISCARDS the old index instead of making it a column
   - Still has 23 columns of data (same as original)
   - Result: You only see the unnamed index, no 'index' column

The 'unnamed index' you see is just how pandas displays the row numbers.
It's not actually a column - it's the index of the dataframe.